language: node_js
sudo: false
node_js:
  - 4
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script:
- npm prune
script: npm run deploy
env:
  global:
    secure: V7qDqj0TGcB9K0H/wtlnxbubUApVC4O32aVNQALMZCtpHBP4vELX0TT6WMRwW0cCpgUonm4sAd8MvJ4BPZAQEFNUSg/yylyMc21nlVboFEPoJX6Y1pgXAnBFa9LvdVJR7ISJ9JF2AXl6bkYhbjeHkzCABJsHx4xsNrYi0TrIFXG1S3fCPm4pHW58DR62lA9x3QghMmY2NYZ0oGm3rSNScaOgb/zmYJIreZQKZ0rUCc3wBL8chTTS7ZUua0gt+Ra5tX9/vSxBx0qmMTj1MdT76sgOv2xzfkRwzs9aBWFi3zKU3ih36r1z5trjdHhiQkv+vhA6GRQC6L/aqZadUHlnVURvTJ+r6QmbY+hXCNCqmccxeYE1pH8SXeCWB2gOZLCrt7iZ7BTbyNwTb517eqQLQGPXNMLGY102fHZwIrk8zBGzCmnvudlH/QCExCXADEdMj/F1N2bXvibimRaUnAAiJ3Pxxsa+B2BTOW/8yC5BMXLj7+u3jgm8D96f0c61x7mHaSrlTaS0gQPjcKk0go/I600rERuWPEDFH2wvyQwV5vMNzU2/qlRwa79inb6JDLcYI0Ttqbzjd/4o/9c742kZx8t4hIZMo1XiXVY8cU+6fMPwQ6AO+IxjES/4Catezcx6s+Rvj2cJ7prpMtfOMhBHXqAXlk1ynRGE5VlaV7vABdk=
