language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 4
script: npm run build && npm run deploy
env:
  global:
    secure: e0ucoHDyGTvJjxNI/eiznNAEkT99Ms268E2yJfYY3bJLgzKpyD5Ks0Xy4bm59tP6lR/USrLyRCtDcoo0VJUTZgoBESJripnjmZolOJz75ChklXMQWXmDRK2UJK/B47ITfEvRh2O4s7F3x6mNMdYzOkAML+1+lR+Aty8cXi1chKMvghh+DWuKfVhfgceT0D6xF/AYZHZZPmxxTYVWInfoOv6t7HvDipi9HFL+Vkg0iUC/MMJs7eAAA6uLjZ+fTBoJivja7LbTYgXN/0MFPUSjbtmn0CjJE2XFpbEGa6CgpgdG0sE9KjnVBH0EaxBnVE6MB0R0vCNT4YQK+wzKWqTQXEi2ilSG2oazJRPHXAcdP8/cXGCvgNAau2WnrnJGQzvkxqA9U1jBQsv2CRJkRiQgIANG+ZooLDfbDP0w107eLiFRYEtICgYaOTYdZCRobOTnlUAYQHEWDLFOP/eyPTl7Fg0QpYvYG0SfTJW8fCW4bzj5cdbuqUmSvU4Cwjo89BfPE0fk06z2MNJfTIn5EJm9HHU2YO52UXlOmp6YPk/Obo/GAnjm46KzRkHS3MM+gBZ7o510dDnE1IeXUBkacNFivJgTFfM0cr+TKovSw+y/5JzZUWuKTMwio3k9+hIYBAfOiR70bsPwLmB7myaqdUrntXsw82LwFS5DTAFDJUifsBQ=
